import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:task_management/features/data/local/models/category.dart';
import 'package:task_management/features/data/local/models/status.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'task.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'task.g.dart';

@freezed
class Task with _$Task {
  const factory Task({
    required String title,
    required String description,
    required DateTime date,
    required String address,
    required Status  status,
    required Category category,
  }) = _Task;

  factory Task.fromJson(Map<String, Object?> json)
  => _$TaskFromJson(json);
}